### ISSUE TITLE
错误，返回信息：getaddrinfo EAI_AGAIN （地址）

### ISSUE THREAD

**Issue by jerrywcy** [HenryQW/mercury-parser-api#111]
- **Platform**:Linux iZuf63oqyjp30wx07gi8jvZ 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Mercury Parser API Version**:latest
- **Node Version**:v10.19.0

## Expected Behavior

返回结果

## Current Behavior

{"error":true,"messages":"getaddrinfo EAI_AGAIN china.caixin.com"}

用别的链接也是这样，只是后面的地址改了，README.md里的例子也是一样

## Steps to Reproduce

1. 运行`docker run -p 3000:3000 -d mercury-parser-api`
2. 在3000端口使用

或者直接用我的链接：http://139.196.180.51:3000

## Detailed Description

直接到这个链接去

`http://139.196.180.51:3000/parser?url=`

在后面放文章url

## Possible Solution

我上网查了一下

说getaddrinfo的返回值EAI_AGAIN代表`DNS(name server)返回临时性错误. 可以稍后重试.`

但是试多少遍都没有用

**Comment by HenryQW** [comment]
谷歌你这个错误第一条返回的是，你的VPS供应商可能阻止了你的请求。检查你的VPS防火墙，尝试在本地先部署试试看。
