### ISSUE TITLE
Mercury API key

### ISSUE THREAD

**Issue by somedevreally** [HenryQW/mercury-parser-api#127]
where can i get the Mercury API key? am using docker wangqiru/mercury-parser-api

**Comment by HenryQW** [comment]
No API key is needed, see <https://github.com/HenryQW/mercury-parser-api#usage>

**Comment by somedevreally** [comment]
oh ok, i use it with tt-rss, for months now no issue. but this new [service](https://github.com/johnwarne/reddit-top-rss/issues/2#issuecomment-626407238) needs an api, so wanted to check
thanks
