### ISSUE TITLE
Argument contentType doesn't work

### ISSUE THREAD

**Issue by ilona-grabowicz** [HenryQW/mercury-parser-api#144]
Hi!
I followed the installation and usage lines from your Readme, but the argument contentType does not work. Example:

curl localhost:3000/parser?url=https://www.bbc.co.uk/news/science-environment-35876621&contentType='text'

returns exactly the same result (the html format) as the line without contentType argument. Could please provide information how to use it to make it work?

Best

**Comment by HenryQW** [comment]
The contentType refers to the [MIME header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type).

You have misunderstood the usage.

**Comment by ilona-grabowicz** [comment]
Hmm, OK. Is then any way to use your docker to get content as text, instead
of html??

pon., 27 lip 2020 o 16:18 Henry Wang <notifications@github.com> napisał(a):

**Comment by HenryQW** [comment]
No, it's not designed for that purpose.
