### ISSUE TITLE
Site Parsing Issue Q

### ISSUE THREAD

**Issue by Organizer21** [HenryQW/mercury-parser-api#179]
Hi there Henry, I am running this with my NAS and a TTRSS build and generally all work well.

However I have just noticed it is having issues with at least one site. Now, I am a bit new to this and was hoping you had a tip or two how it potentially could be fixed as a fellow user. I did not at glance see a way to customize anything on a per feed basis and I believe your build is the latest one there is (it feels like the postlight version has not been maintained for a good while).

This site seems to pull the text, but also the text for multiple articles below it:
https://www.thumbsticks.com/nintendo-switch-releases-september-21-25-2020-09242020/

**Comment by HenryQW** [comment]
I believe you are right, this is a postlight parser issue. The parser is generally not compatible with those feed layout websites, unless a custom rule is merged into [their repo](https://github.com/postlight/mercury-parser/tree/master/src/extractors/custom).

There is nothing I can do in this repo.
